# General configruation

title: Anya's Blog
description: >
  Welcome to my blog!
baseurl: "" 
url: "https://anyasciiTV.github.io" 
theme: hacker
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  #- jekyll-feed
  #- jekyll-seo-tag

# Additional optional configurations
#permalink: pretty

# Creator information

author:
  name: Anya
  email: anyascii@gmail.com

# Social media links

#social:
  #github: anyasciiTV
  #twitch: twitch.tv/anyascii
  #youtube: youtube.com/@anyascii
  #twitter: twitter.com/4NY4SCII

