# General configruation

title: Anya's Command Line Chronicles
description: "A place for all things tech"
baseurl: "" 
url: "https://anyasciiTV.github.io" 
logo: 'docs/assets/images/tux500.png'
#favicon: 'assets/favicon.png'
theme: hacker
markdown: kramdown
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - category
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Additional optional configurations
#permalink: pretty

# Creator information

author:
  name: Anya
  display_name: anyascii
  avatar: 'docs/assets/images/tux500.png'
  email: anyascii@gmail.com

# Social media links

social:
  github: anyasciiTV
  twitch: twitch.tv/anyascii
  youtube: youtube.com/@anyascii
  twitter: twitter.com/4NY4SCII

# Lazy images
lazyimages: "enabled"
