title: Anya's Blog
email: anyascii@gmail.com
description: >
  Welcome to my blog!
baseurl: "" 
url: "https://anyasciiTV.github.io" 
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

# Additional optional configurations
permalink: pretty
